// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// FourHundredAndFourCode - A short code indicating the error code returned.
type FourHundredAndFourCode string

const (
	FourHundredAndFourCodeNotFound FourHundredAndFourCode = "not_found"
)

func (e FourHundredAndFourCode) ToPointer() *FourHundredAndFourCode {
	return &e
}
func (e *FourHundredAndFourCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "not_found":
		*e = FourHundredAndFourCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FourHundredAndFourCode: %v", v)
	}
}

type FourHundredAndFourError struct {
	// A short code indicating the error code returned.
	Code FourHundredAndFourCode `json:"code"`
	// A human readable explanation of what went wrong.
	Message string `json:"message"`
	// A link to our documentation with more details about this error code
	DocURL *string `json:"doc_url,omitempty"`
}

func (o *FourHundredAndFourError) GetCode() FourHundredAndFourCode {
	if o == nil {
		return FourHundredAndFourCode("")
	}
	return o.Code
}

func (o *FourHundredAndFourError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *FourHundredAndFourError) GetDocURL() *string {
	if o == nil {
		return nil
	}
	return o.DocURL
}

// FourHundredAndFour - The server cannot find the requested resource.
type FourHundredAndFour struct {
	Error FourHundredAndFourError `json:"error"`
}

func (o *FourHundredAndFour) GetError() FourHundredAndFourError {
	if o == nil {
		return FourHundredAndFourError{}
	}
	return o.Error
}
