workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Dub API:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: .speakeasy/terraform-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/ryan-blunden-74v/terraform/dub-api
targets:
    dub:
        target: terraform
        source: Dub API
