// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	tfTypes "github.com/ryan-blunden/terraform-provider-dub/internal/provider/types"
	"github.com/ryan-blunden/terraform-provider-dub/internal/sdk/models/operations"
	"github.com/ryan-blunden/terraform-provider-dub/internal/sdk/models/shared"
)

func (r *LinkDataSourceModel) ToOperationsGetLinkInfoRequest(ctx context.Context) (*operations.GetLinkInfoRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	domain := new(string)
	if !r.Domain.IsUnknown() && !r.Domain.IsNull() {
		*domain = r.Domain.ValueString()
	} else {
		domain = nil
	}
	key := new(string)
	if !r.Key.IsUnknown() && !r.Key.IsNull() {
		*key = r.Key.ValueString()
	} else {
		key = nil
	}
	var id string
	id = r.ID.ValueString()

	externalID := new(string)
	if !r.ExternalID.IsUnknown() && !r.ExternalID.IsNull() {
		*externalID = r.ExternalID.ValueString()
	} else {
		externalID = nil
	}
	out := operations.GetLinkInfoRequest{
		Domain:     domain,
		Key:        key,
		ID:         id,
		ExternalID: externalID,
	}

	return &out, diags
}

func (r *LinkDataSourceModel) RefreshFromSharedLinkSchema(ctx context.Context, resp *shared.LinkSchema) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Android = types.StringPointerValue(resp.Android)
		r.Archived = types.BoolPointerValue(resp.Archived)
		r.Clicks = types.Float64PointerValue(resp.Clicks)
		r.Comments = types.StringPointerValue(resp.Comments)
		r.CreatedAt = types.StringValue(resp.CreatedAt)
		r.Description = types.StringPointerValue(resp.Description)
		r.DoIndex = types.BoolPointerValue(resp.DoIndex)
		r.Domain = types.StringValue(resp.Domain)
		r.ExpiredURL = types.StringPointerValue(resp.ExpiredURL)
		r.ExpiresAt = types.StringPointerValue(resp.ExpiresAt)
		r.ExternalID = types.StringPointerValue(resp.ExternalID)
		r.FolderID = types.StringPointerValue(resp.FolderID)
		if resp.Geo == nil {
			r.Geo = nil
		} else {
			r.Geo = &tfTypes.Geo{}
			r.Geo.Ad = types.StringPointerValue(resp.Geo.Ad)
			r.Geo.Ae = types.StringPointerValue(resp.Geo.Ae)
			r.Geo.Af = types.StringPointerValue(resp.Geo.Af)
			r.Geo.Ag = types.StringPointerValue(resp.Geo.Ag)
			r.Geo.Ai = types.StringPointerValue(resp.Geo.Ai)
			r.Geo.Al = types.StringPointerValue(resp.Geo.Al)
			r.Geo.Am = types.StringPointerValue(resp.Geo.Am)
			r.Geo.Ao = types.StringPointerValue(resp.Geo.Ao)
			r.Geo.Aq = types.StringPointerValue(resp.Geo.Aq)
			r.Geo.Ar = types.StringPointerValue(resp.Geo.Ar)
			r.Geo.As = types.StringPointerValue(resp.Geo.As)
			r.Geo.At = types.StringPointerValue(resp.Geo.At)
			r.Geo.Au = types.StringPointerValue(resp.Geo.Au)
			r.Geo.Aw = types.StringPointerValue(resp.Geo.Aw)
			r.Geo.Ax = types.StringPointerValue(resp.Geo.Ax)
			r.Geo.Az = types.StringPointerValue(resp.Geo.Az)
			r.Geo.Ba = types.StringPointerValue(resp.Geo.Ba)
			r.Geo.Bb = types.StringPointerValue(resp.Geo.Bb)
			r.Geo.Bd = types.StringPointerValue(resp.Geo.Bd)
			r.Geo.Be = types.StringPointerValue(resp.Geo.Be)
			r.Geo.Bf = types.StringPointerValue(resp.Geo.Bf)
			r.Geo.Bg = types.StringPointerValue(resp.Geo.Bg)
			r.Geo.Bh = types.StringPointerValue(resp.Geo.Bh)
			r.Geo.Bi = types.StringPointerValue(resp.Geo.Bi)
			r.Geo.Bj = types.StringPointerValue(resp.Geo.Bj)
			r.Geo.Bl = types.StringPointerValue(resp.Geo.Bl)
			r.Geo.Bm = types.StringPointerValue(resp.Geo.Bm)
			r.Geo.Bn = types.StringPointerValue(resp.Geo.Bn)
			r.Geo.Bo = types.StringPointerValue(resp.Geo.Bo)
			r.Geo.Bq = types.StringPointerValue(resp.Geo.Bq)
			r.Geo.Br = types.StringPointerValue(resp.Geo.Br)
			r.Geo.Bs = types.StringPointerValue(resp.Geo.Bs)
			r.Geo.Bt = types.StringPointerValue(resp.Geo.Bt)
			r.Geo.Bv = types.StringPointerValue(resp.Geo.Bv)
			r.Geo.Bw = types.StringPointerValue(resp.Geo.Bw)
			r.Geo.By = types.StringPointerValue(resp.Geo.By)
			r.Geo.Bz = types.StringPointerValue(resp.Geo.Bz)
			r.Geo.Ca = types.StringPointerValue(resp.Geo.Ca)
			r.Geo.Cc = types.StringPointerValue(resp.Geo.Cc)
			r.Geo.Cd = types.StringPointerValue(resp.Geo.Cd)
			r.Geo.Cf = types.StringPointerValue(resp.Geo.Cf)
			r.Geo.Cg = types.StringPointerValue(resp.Geo.Cg)
			r.Geo.Ch = types.StringPointerValue(resp.Geo.Ch)
			r.Geo.Ci = types.StringPointerValue(resp.Geo.Ci)
			r.Geo.Ck = types.StringPointerValue(resp.Geo.Ck)
			r.Geo.Cl = types.StringPointerValue(resp.Geo.Cl)
			r.Geo.Cm = types.StringPointerValue(resp.Geo.Cm)
			r.Geo.Cn = types.StringPointerValue(resp.Geo.Cn)
			r.Geo.Co = types.StringPointerValue(resp.Geo.Co)
			r.Geo.Cr = types.StringPointerValue(resp.Geo.Cr)
			r.Geo.Cu = types.StringPointerValue(resp.Geo.Cu)
			r.Geo.Cv = types.StringPointerValue(resp.Geo.Cv)
			r.Geo.Cw = types.StringPointerValue(resp.Geo.Cw)
			r.Geo.Cx = types.StringPointerValue(resp.Geo.Cx)
			r.Geo.Cy = types.StringPointerValue(resp.Geo.Cy)
			r.Geo.Cz = types.StringPointerValue(resp.Geo.Cz)
			r.Geo.De = types.StringPointerValue(resp.Geo.De)
			r.Geo.Dj = types.StringPointerValue(resp.Geo.Dj)
			r.Geo.Dk = types.StringPointerValue(resp.Geo.Dk)
			r.Geo.Dm = types.StringPointerValue(resp.Geo.Dm)
			r.Geo.Do = types.StringPointerValue(resp.Geo.Do)
			r.Geo.Dz = types.StringPointerValue(resp.Geo.Dz)
			r.Geo.Ec = types.StringPointerValue(resp.Geo.Ec)
			r.Geo.Ee = types.StringPointerValue(resp.Geo.Ee)
			r.Geo.Eg = types.StringPointerValue(resp.Geo.Eg)
			r.Geo.Eh = types.StringPointerValue(resp.Geo.Eh)
			r.Geo.Er = types.StringPointerValue(resp.Geo.Er)
			r.Geo.Es = types.StringPointerValue(resp.Geo.Es)
			r.Geo.Et = types.StringPointerValue(resp.Geo.Et)
			r.Geo.Fi = types.StringPointerValue(resp.Geo.Fi)
			r.Geo.Fj = types.StringPointerValue(resp.Geo.Fj)
			r.Geo.Fk = types.StringPointerValue(resp.Geo.Fk)
			r.Geo.Fm = types.StringPointerValue(resp.Geo.Fm)
			r.Geo.Fo = types.StringPointerValue(resp.Geo.Fo)
			r.Geo.Fr = types.StringPointerValue(resp.Geo.Fr)
			r.Geo.Ga = types.StringPointerValue(resp.Geo.Ga)
			r.Geo.Gb = types.StringPointerValue(resp.Geo.Gb)
			r.Geo.Gd = types.StringPointerValue(resp.Geo.Gd)
			r.Geo.Ge = types.StringPointerValue(resp.Geo.Ge)
			r.Geo.Gf = types.StringPointerValue(resp.Geo.Gf)
			r.Geo.Gg = types.StringPointerValue(resp.Geo.Gg)
			r.Geo.Gh = types.StringPointerValue(resp.Geo.Gh)
			r.Geo.Gi = types.StringPointerValue(resp.Geo.Gi)
			r.Geo.Gl = types.StringPointerValue(resp.Geo.Gl)
			r.Geo.Gm = types.StringPointerValue(resp.Geo.Gm)
			r.Geo.Gn = types.StringPointerValue(resp.Geo.Gn)
			r.Geo.Gp = types.StringPointerValue(resp.Geo.Gp)
			r.Geo.Gq = types.StringPointerValue(resp.Geo.Gq)
			r.Geo.Gr = types.StringPointerValue(resp.Geo.Gr)
			r.Geo.Gs = types.StringPointerValue(resp.Geo.Gs)
			r.Geo.Gt = types.StringPointerValue(resp.Geo.Gt)
			r.Geo.Gu = types.StringPointerValue(resp.Geo.Gu)
			r.Geo.Gw = types.StringPointerValue(resp.Geo.Gw)
			r.Geo.Gy = types.StringPointerValue(resp.Geo.Gy)
			r.Geo.Hk = types.StringPointerValue(resp.Geo.Hk)
			r.Geo.Hm = types.StringPointerValue(resp.Geo.Hm)
			r.Geo.Hn = types.StringPointerValue(resp.Geo.Hn)
			r.Geo.Hr = types.StringPointerValue(resp.Geo.Hr)
			r.Geo.Ht = types.StringPointerValue(resp.Geo.Ht)
			r.Geo.Hu = types.StringPointerValue(resp.Geo.Hu)
			r.Geo.ID = types.StringPointerValue(resp.Geo.ID)
			r.Geo.Ie = types.StringPointerValue(resp.Geo.Ie)
			r.Geo.Il = types.StringPointerValue(resp.Geo.Il)
			r.Geo.Im = types.StringPointerValue(resp.Geo.Im)
			r.Geo.In = types.StringPointerValue(resp.Geo.In)
			r.Geo.Io = types.StringPointerValue(resp.Geo.Io)
			r.Geo.Iq = types.StringPointerValue(resp.Geo.Iq)
			r.Geo.Ir = types.StringPointerValue(resp.Geo.Ir)
			r.Geo.Is = types.StringPointerValue(resp.Geo.Is)
			r.Geo.It = types.StringPointerValue(resp.Geo.It)
			r.Geo.Je = types.StringPointerValue(resp.Geo.Je)
			r.Geo.Jm = types.StringPointerValue(resp.Geo.Jm)
			r.Geo.Jo = types.StringPointerValue(resp.Geo.Jo)
			r.Geo.Jp = types.StringPointerValue(resp.Geo.Jp)
			r.Geo.Ke = types.StringPointerValue(resp.Geo.Ke)
			r.Geo.Kg = types.StringPointerValue(resp.Geo.Kg)
			r.Geo.Kh = types.StringPointerValue(resp.Geo.Kh)
			r.Geo.Ki = types.StringPointerValue(resp.Geo.Ki)
			r.Geo.Km = types.StringPointerValue(resp.Geo.Km)
			r.Geo.Kn = types.StringPointerValue(resp.Geo.Kn)
			r.Geo.Kp = types.StringPointerValue(resp.Geo.Kp)
			r.Geo.Kr = types.StringPointerValue(resp.Geo.Kr)
			r.Geo.Kw = types.StringPointerValue(resp.Geo.Kw)
			r.Geo.Ky = types.StringPointerValue(resp.Geo.Ky)
			r.Geo.Kz = types.StringPointerValue(resp.Geo.Kz)
			r.Geo.La = types.StringPointerValue(resp.Geo.La)
			r.Geo.Lb = types.StringPointerValue(resp.Geo.Lb)
			r.Geo.Lc = types.StringPointerValue(resp.Geo.Lc)
			r.Geo.Li = types.StringPointerValue(resp.Geo.Li)
			r.Geo.Lk = types.StringPointerValue(resp.Geo.Lk)
			r.Geo.Lr = types.StringPointerValue(resp.Geo.Lr)
			r.Geo.Ls = types.StringPointerValue(resp.Geo.Ls)
			r.Geo.Lt = types.StringPointerValue(resp.Geo.Lt)
			r.Geo.Lu = types.StringPointerValue(resp.Geo.Lu)
			r.Geo.Lv = types.StringPointerValue(resp.Geo.Lv)
			r.Geo.Ly = types.StringPointerValue(resp.Geo.Ly)
			r.Geo.Ma = types.StringPointerValue(resp.Geo.Ma)
			r.Geo.Mc = types.StringPointerValue(resp.Geo.Mc)
			r.Geo.Md = types.StringPointerValue(resp.Geo.Md)
			r.Geo.Me = types.StringPointerValue(resp.Geo.Me)
			r.Geo.Mf = types.StringPointerValue(resp.Geo.Mf)
			r.Geo.Mg = types.StringPointerValue(resp.Geo.Mg)
			r.Geo.Mh = types.StringPointerValue(resp.Geo.Mh)
			r.Geo.Mk = types.StringPointerValue(resp.Geo.Mk)
			r.Geo.Ml = types.StringPointerValue(resp.Geo.Ml)
			r.Geo.Mm = types.StringPointerValue(resp.Geo.Mm)
			r.Geo.Mn = types.StringPointerValue(resp.Geo.Mn)
			r.Geo.Mo = types.StringPointerValue(resp.Geo.Mo)
			r.Geo.Mp = types.StringPointerValue(resp.Geo.Mp)
			r.Geo.Mq = types.StringPointerValue(resp.Geo.Mq)
			r.Geo.Mr = types.StringPointerValue(resp.Geo.Mr)
			r.Geo.Ms = types.StringPointerValue(resp.Geo.Ms)
			r.Geo.Mt = types.StringPointerValue(resp.Geo.Mt)
			r.Geo.Mu = types.StringPointerValue(resp.Geo.Mu)
			r.Geo.Mv = types.StringPointerValue(resp.Geo.Mv)
			r.Geo.Mw = types.StringPointerValue(resp.Geo.Mw)
			r.Geo.Mx = types.StringPointerValue(resp.Geo.Mx)
			r.Geo.My = types.StringPointerValue(resp.Geo.My)
			r.Geo.Mz = types.StringPointerValue(resp.Geo.Mz)
			r.Geo.Na = types.StringPointerValue(resp.Geo.Na)
			r.Geo.Nc = types.StringPointerValue(resp.Geo.Nc)
			r.Geo.Ne = types.StringPointerValue(resp.Geo.Ne)
			r.Geo.Nf = types.StringPointerValue(resp.Geo.Nf)
			r.Geo.Ng = types.StringPointerValue(resp.Geo.Ng)
			r.Geo.Ni = types.StringPointerValue(resp.Geo.Ni)
			r.Geo.Nl = types.StringPointerValue(resp.Geo.Nl)
			r.Geo.No = types.StringPointerValue(resp.Geo.No)
			r.Geo.Np = types.StringPointerValue(resp.Geo.Np)
			r.Geo.Nr = types.StringPointerValue(resp.Geo.Nr)
			r.Geo.Nu = types.StringPointerValue(resp.Geo.Nu)
			r.Geo.Nz = types.StringPointerValue(resp.Geo.Nz)
			r.Geo.Om = types.StringPointerValue(resp.Geo.Om)
			r.Geo.Pa = types.StringPointerValue(resp.Geo.Pa)
			r.Geo.Pe = types.StringPointerValue(resp.Geo.Pe)
			r.Geo.Pf = types.StringPointerValue(resp.Geo.Pf)
			r.Geo.Pg = types.StringPointerValue(resp.Geo.Pg)
			r.Geo.Ph = types.StringPointerValue(resp.Geo.Ph)
			r.Geo.Pk = types.StringPointerValue(resp.Geo.Pk)
			r.Geo.Pl = types.StringPointerValue(resp.Geo.Pl)
			r.Geo.Pm = types.StringPointerValue(resp.Geo.Pm)
			r.Geo.Pn = types.StringPointerValue(resp.Geo.Pn)
			r.Geo.Pr = types.StringPointerValue(resp.Geo.Pr)
			r.Geo.Ps = types.StringPointerValue(resp.Geo.Ps)
			r.Geo.Pt = types.StringPointerValue(resp.Geo.Pt)
			r.Geo.Pw = types.StringPointerValue(resp.Geo.Pw)
			r.Geo.Py = types.StringPointerValue(resp.Geo.Py)
			r.Geo.Qa = types.StringPointerValue(resp.Geo.Qa)
			r.Geo.Re = types.StringPointerValue(resp.Geo.Re)
			r.Geo.Ro = types.StringPointerValue(resp.Geo.Ro)
			r.Geo.Rs = types.StringPointerValue(resp.Geo.Rs)
			r.Geo.Ru = types.StringPointerValue(resp.Geo.Ru)
			r.Geo.Rw = types.StringPointerValue(resp.Geo.Rw)
			r.Geo.Sa = types.StringPointerValue(resp.Geo.Sa)
			r.Geo.Sb = types.StringPointerValue(resp.Geo.Sb)
			r.Geo.Sc = types.StringPointerValue(resp.Geo.Sc)
			r.Geo.Sd = types.StringPointerValue(resp.Geo.Sd)
			r.Geo.Se = types.StringPointerValue(resp.Geo.Se)
			r.Geo.Sg = types.StringPointerValue(resp.Geo.Sg)
			r.Geo.Sh = types.StringPointerValue(resp.Geo.Sh)
			r.Geo.Si = types.StringPointerValue(resp.Geo.Si)
			r.Geo.Sj = types.StringPointerValue(resp.Geo.Sj)
			r.Geo.Sk = types.StringPointerValue(resp.Geo.Sk)
			r.Geo.Sl = types.StringPointerValue(resp.Geo.Sl)
			r.Geo.Sm = types.StringPointerValue(resp.Geo.Sm)
			r.Geo.Sn = types.StringPointerValue(resp.Geo.Sn)
			r.Geo.So = types.StringPointerValue(resp.Geo.So)
			r.Geo.Sr = types.StringPointerValue(resp.Geo.Sr)
			r.Geo.Ss = types.StringPointerValue(resp.Geo.Ss)
			r.Geo.St = types.StringPointerValue(resp.Geo.St)
			r.Geo.Sv = types.StringPointerValue(resp.Geo.Sv)
			r.Geo.Sx = types.StringPointerValue(resp.Geo.Sx)
			r.Geo.Sy = types.StringPointerValue(resp.Geo.Sy)
			r.Geo.Sz = types.StringPointerValue(resp.Geo.Sz)
			r.Geo.Tc = types.StringPointerValue(resp.Geo.Tc)
			r.Geo.Td = types.StringPointerValue(resp.Geo.Td)
			r.Geo.Tf = types.StringPointerValue(resp.Geo.Tf)
			r.Geo.Tg = types.StringPointerValue(resp.Geo.Tg)
			r.Geo.Th = types.StringPointerValue(resp.Geo.Th)
			r.Geo.Tj = types.StringPointerValue(resp.Geo.Tj)
			r.Geo.Tk = types.StringPointerValue(resp.Geo.Tk)
			r.Geo.Tl = types.StringPointerValue(resp.Geo.Tl)
			r.Geo.Tm = types.StringPointerValue(resp.Geo.Tm)
			r.Geo.Tn = types.StringPointerValue(resp.Geo.Tn)
			r.Geo.To = types.StringPointerValue(resp.Geo.To)
			r.Geo.Tr = types.StringPointerValue(resp.Geo.Tr)
			r.Geo.Tt = types.StringPointerValue(resp.Geo.Tt)
			r.Geo.Tv = types.StringPointerValue(resp.Geo.Tv)
			r.Geo.Tw = types.StringPointerValue(resp.Geo.Tw)
			r.Geo.Tz = types.StringPointerValue(resp.Geo.Tz)
			r.Geo.Ua = types.StringPointerValue(resp.Geo.Ua)
			r.Geo.Ug = types.StringPointerValue(resp.Geo.Ug)
			r.Geo.Um = types.StringPointerValue(resp.Geo.Um)
			r.Geo.Us = types.StringPointerValue(resp.Geo.Us)
			r.Geo.Uy = types.StringPointerValue(resp.Geo.Uy)
			r.Geo.Uz = types.StringPointerValue(resp.Geo.Uz)
			r.Geo.Va = types.StringPointerValue(resp.Geo.Va)
			r.Geo.Vc = types.StringPointerValue(resp.Geo.Vc)
			r.Geo.Ve = types.StringPointerValue(resp.Geo.Ve)
			r.Geo.Vg = types.StringPointerValue(resp.Geo.Vg)
			r.Geo.Vi = types.StringPointerValue(resp.Geo.Vi)
			r.Geo.Vn = types.StringPointerValue(resp.Geo.Vn)
			r.Geo.Vu = types.StringPointerValue(resp.Geo.Vu)
			r.Geo.Wf = types.StringPointerValue(resp.Geo.Wf)
			r.Geo.Ws = types.StringPointerValue(resp.Geo.Ws)
			r.Geo.Xk = types.StringPointerValue(resp.Geo.Xk)
			r.Geo.Ye = types.StringPointerValue(resp.Geo.Ye)
			r.Geo.Yt = types.StringPointerValue(resp.Geo.Yt)
			r.Geo.Za = types.StringPointerValue(resp.Geo.Za)
			r.Geo.Zm = types.StringPointerValue(resp.Geo.Zm)
			r.Geo.Zw = types.StringPointerValue(resp.Geo.Zw)
		}
		r.ID = types.StringValue(resp.ID)
		r.Image = types.StringPointerValue(resp.Image)
		r.Ios = types.StringPointerValue(resp.Ios)
		r.Key = types.StringValue(resp.Key)
		r.LastClicked = types.StringPointerValue(resp.LastClicked)
		r.Leads = types.Float64PointerValue(resp.Leads)
		r.PartnerID = types.StringPointerValue(resp.PartnerID)
		r.Password = types.StringPointerValue(resp.Password)
		r.ProgramID = types.StringPointerValue(resp.ProgramID)
		r.ProjectID = types.StringValue(resp.ProjectID)
		r.Proxy = types.BoolPointerValue(resp.Proxy)
		r.PublicStats = types.BoolPointerValue(resp.PublicStats)
		r.QrCode = types.StringValue(resp.QrCode)
		r.Rewrite = types.BoolPointerValue(resp.Rewrite)
		r.SaleAmount = types.Float64PointerValue(resp.SaleAmount)
		r.Sales = types.Float64PointerValue(resp.Sales)
		r.ShortLink = types.StringValue(resp.ShortLink)
		r.TagID = types.StringPointerValue(resp.TagID)
		if resp.Tags != nil {
			r.Tags = []tfTypes.TagSchema{}
			if len(r.Tags) > len(resp.Tags) {
				r.Tags = r.Tags[:len(resp.Tags)]
			}
			for tagsCount, tagsItem := range resp.Tags {
				var tags tfTypes.TagSchema
				tags.Color = types.StringValue(string(tagsItem.Color))
				tags.ID = types.StringValue(tagsItem.ID)
				tags.Name = types.StringValue(tagsItem.Name)
				if tagsCount+1 > len(r.Tags) {
					r.Tags = append(r.Tags, tags)
				} else {
					r.Tags[tagsCount].Color = tags.Color
					r.Tags[tagsCount].ID = tags.ID
					r.Tags[tagsCount].Name = tags.Name
				}
			}
		}
		r.TenantID = types.StringPointerValue(resp.TenantID)
		r.TestCompletedAt = types.StringPointerValue(resp.TestCompletedAt)
		r.TestStartedAt = types.StringPointerValue(resp.TestStartedAt)
		if resp.TestVariants != nil {
			r.TestVariants = []tfTypes.TestVariant{}
			if len(r.TestVariants) > len(resp.TestVariants) {
				r.TestVariants = r.TestVariants[:len(resp.TestVariants)]
			}
			for testVariantsCount, testVariantsItem := range resp.TestVariants {
				var testVariants tfTypes.TestVariant
				testVariants.Percentage = types.Float64Value(testVariantsItem.Percentage)
				testVariants.URL = types.StringValue(testVariantsItem.URL)
				if testVariantsCount+1 > len(r.TestVariants) {
					r.TestVariants = append(r.TestVariants, testVariants)
				} else {
					r.TestVariants[testVariantsCount].Percentage = testVariants.Percentage
					r.TestVariants[testVariantsCount].URL = testVariants.URL
				}
			}
		}
		r.Title = types.StringPointerValue(resp.Title)
		r.TrackConversion = types.BoolPointerValue(resp.TrackConversion)
		r.UpdatedAt = types.StringValue(resp.UpdatedAt)
		r.URL = types.StringValue(resp.URL)
		r.UserID = types.StringPointerValue(resp.UserID)
		r.UtmCampaign = types.StringPointerValue(resp.UtmCampaign)
		r.UtmContent = types.StringPointerValue(resp.UtmContent)
		r.UtmMedium = types.StringPointerValue(resp.UtmMedium)
		r.UtmSource = types.StringPointerValue(resp.UtmSource)
		r.UtmTerm = types.StringPointerValue(resp.UtmTerm)
		r.Video = types.StringPointerValue(resp.Video)
		r.WebhookIds = make([]types.String, 0, len(resp.WebhookIds))
		for _, v := range resp.WebhookIds {
			r.WebhookIds = append(r.WebhookIds, types.StringValue(v))
		}
		r.WorkspaceID = types.StringValue(resp.WorkspaceID)
	}

	return diags
}
