// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type TestVariant struct {
	Percentage types.Float64 `tfsdk:"percentage"`
	URL        types.String  `tfsdk:"url"`
}
